version: "3.8"

services:
  # Airflow service
  airflow:
    image: ${IMAGE_NAME}
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AIRFLOW_EMAIL=${AIRFLOW_EMAIL}
      - AIRFLOW_USERNAME=${AIRFLOW_USERNAME}
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}
    volumes:
      - ./airflow:/app/airflow
    restart: always
    networks:
      - airflow-streamlit

  # Streamlit service
  streamlit:
    image: ${IMAGE_NAME}
    container_name: streamlit
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_APP_PORT=${STREAMLIT_APP_PORT}
    volumes:
      - ./streamlit:/app/streamlit
    restart: always
    networks:
      - airflow-streamlit

networks:
  airflow-streamlit:
    driver: bridge
