version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow:
    image: apache/airflow:2.9.0-python3.9
    container_name: airflow_container
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW_EMAIL: ${AIRFLOW_EMAIL}
      AIRFLOW_USERNAME: ${AIRFLOW_USERNAME}
      AIRFLOW_PASSWORD: ${AIRFLOW_PASSWORD}
      BUCKET_NAME: ${BUCKET_NAME}
      MONGO_DB_URL: ${MONGO_DB_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_REGION}
    command: ["sh", "-c", "./start.sh"]

  streamlit:
    image: ${IMAGE_NAME}
    container_name: streamlit_container
    depends_on:
      - airflow
    ports:
      - "8501:8501"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      BUCKET_NAME: ${BUCKET_NAME}
    command: >
      sh -c "streamlit run app.py --server.port 8501 --server.address=0.0.0.0 --server.enableCORS false && exec tail -f /dev/null"
